FROM node:22-alpine

LABEL "language"="nodejs"

WORKDIR /app

COPY package*.json ./

RUN npm install --production

COPY server ./server
COPY .env* ./

EXPOSE 3001

CMD ["node", "server/simple-server.js"]
